### ISSUE TITLE
Release 20.11

### ISSUE THREAD

**Issue by imustafin** [tioui/EiffelStudio-GPL-Releases#1]
Hi. I couldn't find the official source code download for the 20.11 release but judging by the filename at https://account.eiffel.com/downloads being [Eiffel_20.11_rev_**105048**-linux-x86-64.tar.bz2](https://www.eiffel.com/cdn/EiffelStudio/20.11/105048/Eiffel_20.11_rev_105048-linux-x86-64.tar.bz2) we can get the respective source code from
https://ftp.eiffel.com/pub/beta/latest/eiffelstudio-20.11.10.5048.tar.

What do you think? Would it make sense to make a 20.11 release here with the privacy patches?

Or is there another reason for the absence of the release here?

**Comment by tioui** [comment]
It is not clear if this that this file is licensed GPL or not. 

Know that I am currently working on a release for the 21.05 version (105408). I will try to get official release from https://svn.eiffel.com/eiffelstudio-public/trunk/ when it is accessible, but when I missed it, I will get the version accessible and released it.

**Comment by imustafin** [comment]
I see, thanks for the clarification.

Looking forward for 21.05 :)

Big thanks for your efforts!

**Comment by tioui** [comment]
Sadly, the 21.05 released will take a while because EiffelSoftware have modified the Windows build script significatively. Last time, it took me a month to port this script so that it used local files instead of svn checkout so that it does not crash or loop indefinitely. I think that it will be faster this time, but then again, surprises are always possible (good one and bad one).

**Comment by tioui** [comment]
Finally, I just find a way to checkout the 105048 revision from the public svn trunk. So I will see to create the 20.11 in the next month or so.
